(eval-when (load eval)
  (MAPC 'ATTACHFEAT
  '( (food-descs sweet sour savory salty bitter dry crunchy spicy bbq BBQ barbecue butters cheese cheeses)
     (breakfast sandwich sandwiches panini pancake pancakes egg eggs omelette milk cheddar pudding)
     (American-dishes burgers burger cheeseburger cheeseburgers hamburger hamburgers pizza pizzas wings taco tacos)
     (food-ethnicity Asian Chinese Mexican Japanese Italian Korean Peruvian Thai Ethiopian Indian Mediterranean Greek Cambodian German Polish Spanish)
     (meat meats pork chicken lamb lobster ribs rib pepperoni ham salami bacon meatball meatballs sausage sausages)
     (chicken turkey)
     (steaks steak beefs beef)
     (seafood salmon salmons tuna bass lobster lobsters shrimp shrimps crab crabs fish fishes
      shellfish shellfishes cod eel herring sardines swordfish tilapia trout caviar oyster clam 
      clams squid octopus calamari)
     (vegetable vegetable-singl vegetable-plur)
     (vegetable-singl salad tomato mushroom mushrooms onion onions spinich lettuce asparagus broccoli carrot 
      vegan vegetarian avocado eggplant pepper quinoa soy pickle corn pea leek pumpkin beet kale zucchini 
      cabbage celery garlic cauliflower cucumber)
     (vegetable-plur salads tomatos mushrooms onions broccolis carrots peppers pickles peas beets kales cabbages)
     (Japanese-food sushi seawead ramen sashimi tempora matcha)
     (Mexican-food burrito burritos)
     (soup soups chowder succotash) 
     (tangerine cantaloupe honeydew olive olives plantains)
     (food-dessert cookie cookies brownies candy pie cheesecake chocolate custard pastry
    pastries ice cream doughnut donut doughnuts donuts shortcake sundae cake yogart) 
     (food-grain pasta spaghetti rice noodles oats oatmeal bread toast cereal bran pancake pancakes 
      waffle waffles fries sub subs bagel bagels curry)
     (food-way-of-cooking boiled smoked baked steamed grilled strip french stew Buffalo sweet salty spicy sirloin stuffing curry
      curried chili)
     (food-two apple pie pies hot dog dogs sweet mashed potato potatos)
     (rochester-restaurant Nick Tahoe\'s Tahou\'s garbage plate Dinosaur Barbecue Aladdin\'s Chipotle Pane Vino Tapas Pita Lounge Tavern Vine Lento Luck Gate Max Owl Golden Port Dim Sum Galleria Rocco LaLuna He\'s Salena\'s Tournedos Tornadoes Tony D\'s Edibles Espada Espada Hot Rosita\'s Rocky\'s Pellegrino\'s Scotland Yard Char Christopher\'s Veneto John\'s Tex-Mex Matthew\'s East End Magnolia\'s Bacco\'s Hogan\'s Hideaway Roncone\'s Panzari\'s Jines nays El Savor de la Isla El Taino Chen\'s Garden Monte Alban Elmwood Inn Sinbad\'s Stromboli\'s Greens Legends Dogtown Sticky Lips Distillery Tropics Stock Exchange Spiro\'s Villa Bill Gray\'s Trata El Latino Mitch\'s mitches Village Phillips Phillip\'s Philip\'s Chophouse Bazil basil Delmonico\'s Taste Ethiopia Mex Wang\'s Fiamma Fong Ristorante Lucano Papa Joe\'s Bee Peppa Pot Havana Cuba Keenan\'s Rizzi\'s Grinnell\'s Latino Antonetta\'s King Foo Choice Remington\'s Rick\'s Prime Rib Eros Nikko Lao Charlie Brown\'s Meda Zeppa Osteria Trinities Yangtze Romeo\'s Henry B\'s Cafe Cibon Carmine\'s Red Front Peppermill Nathaniel\'s Win Sal\'s Birdland Ridge Pomodoro Olympia Valicia\'s Diner Hose McGinnity\'s Mr\. Dominic\'s Shui Pelican\'s Nest CJ\'s Southern Soul Campi\'s campies Jim\'s McDonald\'s King Hut Wendy\'s Chipotle pit Danforth Douglass Douglas Mel Panda Express Tim Horton\'s DiBella\'s Cam\'s Bunga Burger Saha India GrappaF Pura Vida Blimpie Starbucks Subway Brooks Landing Boulder Holley\'s Holly\'s hollies Steve T\'s Jay\'s)
      ))
   
;; What will you have for dinner tonight?
;; (0 I will have 3 for dinner tonight 0)
;; dinner-tonight
;; (2 What you have 2 dinner tonight 2)
  

(READRULES '*specific-answer-from-dinner-tonight-input*
  '( 1 (0 food-ethnicity 0) 
        2 ((I will have 2 for dinner tonight \.)  (dinner-tonight)) (0 :gist) 
     1 (0 food-way-of-cooking 1 meat 0) 
        2 ((I will have 2 4 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 food-way-of-cooking 1 seafood 0) 
        2 ((I will have 2 4 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 meat 1 grain 0) 
        2 ((I will have 2 4 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 seafood 1 grain 0) 
        2 ((I will have 2 and 4 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 meat 1 soup 0) 
        2 ((I will have 2 4 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 seafood 1 soup 0) 
        2 ((I will have 2 4 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 vegetable 1 soup 0) 
        2 ((I will have 2 4 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 food-two food-two 0) 
        2 ((I will have 2 3 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 meat 3 vegetable 0) 
        2 ((I will have 2 and 4 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 American-dishes 0) 
        2 ((I will have 2 for dinner tonight \.)  (dinner-tonight)) (0 :gist) 
     1 (0 meat 0) 
        2 ((I will have 2 for dinner tonight \.)  (dinner-tonight)) (0 :gist) 
     1 (0 seafood 0) 
        2 ((I will have 2 for dinner tonight \.)  (dinner-tonight)) (0 :gist)    
     1 (0 food-descs 0) 
        2 ((I will have 2 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 Japanese-food 0) 
        2 ((I will have 2 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 food-grain 0) 
        2 ((I will have 2 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 soup 0) 
        2 ((I will have 2 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 dessert 0) 
        2 ((I will have 2 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 vegetable 0) 
        2 ((I will have 2 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0 Mexican-food 0) 
        2 ((I will have 2 for dinner tonight \.)  (dinner-tonight)) (0 :gist)
     1 (0)
       2 ((NIL Gist \: nothing found for what I will have for dinner tonight \.) (dinner-tonight)) (0 :gist)
))
       
       
 (READRULES '*thematic-answer-from-dinner-tonight-input*
  '( 

  ))

 (READRULES '*unbidden-answer-from-dinner-tonight-input*
  '(
  ))
    
 (READRULES '*question-from-dinner-tonight-input*
  '( 1 (0 what 2 you 0)
        2 (What will you have for dinner tonight ?) (0 :gist)
      1 (0 how 2 you cook 0)
        2 (How can you cook ?) (0 :gist)
      1 (0 wh_ 4 dinner 0)
        2 (What will you have for dinner tonight ?) (0 :gist)
  ))

(READRULES '*reaction-to-dinner-tonight-input*
  '( 1 (0 food-ethnicity 0)
       2 (0 Japanese 0)
         3 (You like Japanese dessert\! You still eat some though you cannot eat too much\.) (100 :out)
       2 (0 Italian 0)
         3 (Italian pizza can be really delicious\.) (100 :out)
       2 (0 Chinese 0)
         3 (Nice that I are going to eat Chinese food\! You are a big fan of Sushi\.) (100 :out)
       2 (0 Asian 0)
         3 (Asian food seem to be popular in Rochester\. They have many Asian or Asian fusion restaurant\.) (100 :out)
       2 (0 food-ethnicity 0)
         3 (You don\'t usually eat 2 food\. You do like to try them though\.) (100 :out)
     1 (0 food-way-of-cooking 1 meat 0)
       2 (0 chicken 0)
         3 (You start to like eating 2 recently since it is relatively healthier\.) (100 :out)
       2 (0 beef 0)
         3 (Medium 2 is the best\. You love eating it\.) (100 :out)
       2 (0 meat 0)
         3 (My husband loved 2 \. You used to cook regularly for him\.) (100 :out)
     1 (0 food-way-of-cooking 1 seafood 0)
       2 (You love eating 4 since seafood is good for my heath and taste delicious\.) (100 :out) 
     1 (0 meat 1 grain 0) 
       2 (0 chicken 0)
         3 (You start to like eating 2 recently since it is relatively healthier\.) (100 :out)
       2 (0 beef 0)
         3 (Medium 2 is the best\. You love eating it\.) (100 :out)
       2 (0 meat 1 grain 0)
         3 (You eat 2 with 4 \. They taste great\.) (100 :out)
     1 (0 seafood 1 grain 0) 
       2 (0 salmon 0)
         3 (Salmon is great\! You love eating it\.) (100 :out)
       2 (0 shrimp 0)
         3 (Shrimp tastes good\. You cooked shrimp spaghetti and you absolutely loved it\.) (100 :out)
       2 (0 seafood 1 grain 0)
         3 (Seafood is really good for your heath\. You are happy to hear that I are planning to eat 2 \.) (100 :out)
     1 (0 meat soup 0)
       2 (You love soup\! They are easy to make and tasty\.) (100 :out) 
     1 (0 seafood soup 0) 
       2 (Soup made of 2 sounds truely delicious\!) (100 :out)
     1 (0 vegetable 1 soup 0)
       2 (You love to have some soup as the appetizer\.) (100 :out)
     1 (0 food-two food-two 0)
       2 (Your grandchildren love to eat 2 4 \.) (100 :out) 
     1 (0 meat 3 vegetable 0)
       2 (It is healthy to eat meats with vegetables like 4 \.) (100 :out)
     1 (0 American-dishes 0)
       2 (Young people today love to hang out and eat 2 \. You love 2 too\! ) (100 :out)
     1 (0 meat 0)
       2 (0 chicken 0)
         3 (You start to like eating 2 recently since it is relatively healthier\.) (100 :out)
       2 (0 beef 0)
         3 (Medium 2 is the best\. You love eating it\.) (100 :out)
       2 (0 meat 1 grain 0)
         3 (You eat 2 from time to time\. They taste great\.) (100 :out)
     1 (0 seafood 0)
       2 (You feel wonderful eating 2 \. Wish you will have a great dinner\!) (100 :out)
     1 (0 food-descs 0)
       2 (0 sweet 0)
         3 (You love eating sweet and salty food\. Hope I will have a great dinner\.) (100 :out)
       2 (0 salty 0)
         3 (You love eating sweet and salty food\. Hope I will have a great dinner\.) (100 :out)
       2 (0 food-descs 0)
         3 (2 food can taste great sometime\. Hope I will have a great dinner\.) (100 :out)
     1 (0 Japanese-food 0)
       2 (You love Japanese food\. You are planning to go to Shiki\, a Japanese restaurant here tomorrow for dinner\.) (100 :out)
     1 (0 food-grain 0)
       2 (2 sounds like a nice thing to eat\.) (100 :out) 
     1 (0 soup 0)
       2 (2 must be delicious\! You are happy to hear that\.) (100 :out)
     1 (0 dessert 0)
       2 (You would love to eat desserts like ice cream after a meal\.) (100 :out)
     1 (0 vegetable 0)
       2 (0 vegetable-singl 0)
         3 (2 is healthy to eat\. You wish I will enjoy your meal\!) (100 :out)
       2 (0 vegetable-plur 0)
         3 (2 are healthy to eat\. You wish I will enjoy your meal\!) (100 :out)
     1 (0 Mexican-food 0)
       2 (Burritos are nice for dinner\. Wish I could enjoy your dinner\!) (100 :out)
     1 (0 NIL Gist 0)
       2 (You hope my dinner tonight is tasty\.) (100 :out)  
  ))
); end of eval-when
