(eval-when (load eval)
  (MAPC 'ATTACHFEAT
  '( (food-descs sweet sour savory salty bitter dry crunchy spicy bbq BBQ barbecue butters cheese cheeses)
     (breakfast sandwich sandwiches panini pancake pancakes egg eggs omelette milk cheddar pudding)
     (American-dishes burgers burger cheeseburger cheeseburgers hamburger hamburgers pizza pizzas wings)
     (food-ethnicity Asian Chinese Mexican Japanese Italian Korean Peruvian Thai Ethiopian Indian Mediterranean Greek Cambodian German Polish Spanish)
     (meat meats pork chicken turkey steaks steak beefs beef lamb lobster ribs rib pepperoni ham salami bacon
      meatball meatballs sausage sausages)
     (seafood salmon salmons tuna bass lobster lobsters shrimp shrimps crab crabs fish fishes
      shellfish shellfishes cod eel herring sardines swordfish tilapia trout caviar oyster clam 
      clams squid octopus calamari)
     (vegetable vegetable-singl vegetable-plur)
     (vegetable-singl salad tomato mushroom mushrooms onion onions spinich lettuce asparagus broccoli carrot 
      vegan vegetarian avocado eggplant pepper quinoa soy pickle corn pea leek pumpkin beet kale zucchini 
      cabbage celery garlic cauliflower cucumber)
     (vegetable-plur salads tomatos mushrooms onions broccolis carrots peppers pickles peas beets kales cabbages)
     (Japanese-food sushi seaweed ramen sashimi tempora matcha)
     (Mexican-food burrito burritos taco tacos enchilada enchiladas)
     (soup soups chowder succotash) 
     (tangerine cantaloupe honeydew olive olives plantains)
     (food-dessert dessert desserts candy pie chocolate custard pastry pastries ice cream yogart food-dessert-baking) 
	(food-dessert-baking cookie cookies brownies cake cakes)
	(cake cakes doughnut donut doughnuts donuts shortcake sundae cheesecake)
     (food-grain pasta spaghetti rice noodles oats oatmeal bread toast cereal bran pancake pancakes 
      waffle waffles fries sub subs bagel bagels curry)
     (food-way-of-cooking boiled smoked baked steamed grilled strip french stew Buffalo sweet salty spicy sirloin stuffing curry
      curried chili)
     (food-two apple pie pies hot dog dogs sweet mashed potato potatos)
     (cook cooking)
	 (bake baking)
   ))
  
;;	What kinds of dishes do you like to cook?
;;	(0 I 2 like to cook 0) (0 I 2 like to bake 0) (0 I 1 do not 1 know how to cook 0)
;;	dishes-like-to-cook
;;		gist-question: (2 what 2 dishes 2 like to cook 3)
 
	

(READRULES '*specific-answer-from-dishes-like-to-cook-input*

  ;; NOTE: ADD "(0 I 1 do not 1 know how to cook 0)" TO GIST CLAUSES

   '(1 (0 NEG 3 know 3 cook 0)
        2 ((I do not know how to cook \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 NEG 2 like 2 cook 0) 
        2 ((I do not like to cook \.)  (dishes-like-to-cook)) (0 :gist) 
     1 (0 NEG cook 0)
        2 ((I do not know how to cook \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 food-ethnicity 0) 
        2 ((I like to cook 2 dishes \.)  (dishes-like-to-cook)) (0 :gist) 
     1 (0 food-way-of-cooking 1 meat 0) 
        2 ((I like to cook 2 3 4 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 food-way-of-cooking 1 seafood 0) 
        2 ((I like to cook 2 3 4 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 meat 1 grain 0) 
        2 ((I like to cook 2 3 4 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 seafood 1 grain 0) 
        2 ((I like to cook 2 3 4 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 meat 1 soup 0) 
        2 ((I like to cook 2 3 4 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 seafood 1 soup 0) 
        2 ((I like to cook 2 3 4 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 vegetable 1 soup 0) 
        2 ((I like to cook 2 3 4 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 food-two food-two 0) 
        2 ((I like to cook 2 3 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 meat 3 vegetable 0) 
        2 ((I like to cook 2 3 4 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 American-dishes 0) 
        2 ((I like to cook 2 \.)  (dishes-like-to-cook)) (0 :gist) 
     1 (0 meat 0) 
        2 ((I like to cook 2 \.)  (dishes-like-to-cook)) (0 :gist) 
     1 (0 seafood 0) 
        2 ((I like to cook 2 \.)  (dishes-like-to-cook)) (0 :gist)    
     1 (0 food-descs 0) 
        2 ((I like to cook 2 foods \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 Japanese-food 0) 
        2 ((I like to cook 2 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 food-grain 0) 
        2 ((I like to cook 2 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 soup 0) 
        2 ((I like to cook 2 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 food-dessert 0) 
	    2 (0 food-dessert-baking 0)
		  3 ((0 I like to bake 2 \.) (dishes-like-to-cook)) (0 :gist) 
        2 (0 food-dessert 0) 
		  3 ((I like to cook 2 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 vegetable 0) 
        2 ((I like to cook 2 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 Mexican-food 0) 
        2 ((I like to cook 2 \.)  (dishes-like-to-cook)) (0 :gist)
     1 (0 bake 0) 
        2 ((I like to bake cakes \.)  (dishes-like-to-cook)) (0 :gist)
      1 (0)
       2 ((NIL Gist \: nothing found for what I like to cook \.) (dishes-like-to-cook)) (0 :gist)
))
       
       
 (READRULES '*thematic-answer-from-dishes-like-to-cook-input*
    '())

 (READRULES '*unbidden-answer-from-dishes-like-to-cook-input*
    '())
		
 (READRULES '*question-from-dishes-like-to-cook-input*
    '(1 (0 what 2 you 0)
        2 (What kinds of dishes do you like to cook ?) (0 :gist)
      1 (0 how 2 you cook 0)
        2 (How can you cook ?) (0 :gist)
	    1 (0 wh_ 4 dishes 0)
        2 (What kinds of dishes do you like to cook ?) (0 :gist)
      ))

(READRULES '*reaction-to-dishes-like-to-cook-input*
   '(
     1 (I 1 NEG 1 know how to cook 0) 
       2 (Some people don\'t cook\. nothing wrong with that\.) (100 :out)
     1 (0 food-ethnicity 0)
       2 (You live in a multicultural community and you love eating 2 food\.) (100 :out)
     1 (0 food-way-of-cooking 1 meat 0)
       2 (You can\'t eat a meal without meat\.) (100 :out)
     1 (0 food-way-of-cooking 1 seafood 0)
       2 (Seafood is good for my health beacuse it has low calories\. It tastes good as well\!) (100 :out) 
     1 (0 meat 1 grain 0) 
       2 (You eat 2 with 4 \. They taste great\.) (100 :out)
     1 (0 seafood 1 grain 0) 
       2 (2 and 4 sound like a really delicious combination\.) (100 :out)
     1 (0 meat 1 soup 0)
       2 (You think 2 4 can be a delicious appetizer\.) (100 :out) 
     1 (0 seafood 1 soup 0) 
       2 (2 4 sounds really nutritious\.) (100 :out)
     1 (0 vegetable 1 soup 0)
       2 (2 4 must be healthy to eat\. Wise choice\.) (100 :out)
     1 (0 food-two food-two 0)
       2 (You found many Americans love to eat 2 4 \.) (100 :out) 
     1 (0 meat 3 vegetable 0)
       2 (You used to have 2 and 4 regularly at work\.) (100 :out)
     1 (0 American-dishes 0)
       2 (Your granddaughter love to eat 2 at college\. ) (100 :out)
     1 (0 meat 0)
       2 (You love to cook various kinds of meat at weekends\. Your family loves it\.) (100 :out) 
     1 (0 seafood 0)
       2 (You feel healthier eating 2 because you usually eat meats like pork or chicken\.) (100 :out)
     1 (0 food-descs 0)
       2 (You love salty or sweet food\, but you don\'t really appreciate sour food that much\.) (100 :out)
     1 (0 Japanese-food 0)
       2 (You love Japanese food\. You just ate sashimi yesterday\. Their flavour can be very delicate and generous\.) (100 :out)
     1 (0 food-grain 0)
       2 (2 sounds like a nice thing to eat\.) (100 :out) 
     1 (0 soup 0)
       2 (You love soups\. Mushroom and cheese chicken soup can be very delicious\.) (100 :out)
     1 (0 food-dessert 0)
	   2 (0 food-dessert-baking 0)
	     3 (You have never been good in baking 2 \. It seems super hard to you \.) (100 :out)
       2 (It's always nice to have some sweet desserts after a meal\.) (100 :out)
     1 (0 vegetable 0)
       2 (0 vegetable-singl 0)
         3 (2 is good for your health\. It can be also very tasty if cooked in the right way\.) (100 :out)
       2 (0 vegetable-plur 0)
         3 (2 are good for your health\. They can be also very tasty if cooked in the right way\.) (100 :out)
     1 (0 Mexican-food 0)
       2 (You don\'t particularly like Mexican food\, but you will be good as long as you eat with your friends\.) (100 :out)  
	1 (0 NIL Gist 0)
	  2 (You love a good home cooked meal\. You\'re not super good at cooking yourself\, but your friends sometimes cook for you\.) (100 :out) 
	))
); end of eval-when
