(eval-when (load eval)
  (MAPC 'ATTACHFEAT
  '( (car-brand Chevrolet Ford Mustang Chevrolet Corvair Fiat Chevette Triumph Toyota Celica Simca Aronde Mini Pontiac Oldsmobile
    Dodge Austin Studebaker Plymouth Mercury Cadillac Jeep Chevy Mercedes Mercedes-Benz Volkswagen Vauxhall Morris Garages MG Renault Willys
    Lincoln Packard Buick REO Stutz Franklin Jaguar)
    (Cgevriker Chevy)
    (car-brand-two Maxi Allegro Corvair Mustang Ranger Chevy Nova Celica Corona Aronde Morris Mini Festiva Stylemaster
      Firebird Vista Cruiser Wagon Hawk Convertible Pickup Special Coupe Deluxe Benz Beetle Custom Astra Cutlass Maverick
      Sedan Fleetmaster Continental Special Roadmaster Benz Roadster Bel Air Thunder Bird)
    (shade dark light mint navy)
    (color black brown blue red silver white green gold champagne purple)
    (friend friends)
    (family grandchildren grandchild children child daughter daughters son sons spouse wife husband siblings brother brothers sister sisters
      parents mother father mom dad grandparents grandma grandpa grandmother grandfather)
    (gift gifts present presents)
   ))
  
;;	What do you remember about your first car ?
;;	(0 my first car 0)
;;	first-car
;;		gist-question: (2 what 1 you remember 2 first car 3)  
	

(READRULES '*specific-answer-from-first-car-input*
   '(1 (1 NEG 4 remember 0) 
        2 ((I do not remember things about my first car \.)  (first-car)) (0 :gist)
     1 (0 car-brand 1 car-brand-two 0) 
        2 ((The brand of my first car is 2 4 \.)  (first-car)) (0 :gist) 
     1 (0 car-brand-two 1 car-brand-two 0) 
        2 ((The brand of my first car is 2 4 \.)  (first-car)) (0 :gist)
     1 (0 car-brand 0) 
        2 ((The brand of my first car is 2 \.)  (first-car)) (0 :gist) 
     1 (0 car-brand-two 0) 
        2 ((The brand of my first car is 2 \.)  (first-car)) (0 :gist) 
     1 (0 shade 1 color 0) 
        2 ((The color of my first car is 2 4 \.)  (first-car)) (0 :gist) 
     1 (0 color 0) 
        2 ((The color of my first car is 2 \.)  (first-car)) (0 :gist) 
     1 (0 is 2 gift 0)
        2 (0 gift 3 family 0)
           3 ((My first car is a gift from my 4 \.)  (first-car)) (0 :gist)
        2 (0 family 2 gift 0)
           3 ((My first car is a gift from my 2 \.)  (first-car)) (0 :gist)
        2 (0 gift 0)
           3 ((My first car is a gift \.)  (first-car)) (0 :gist)
     1 (0 mom\'s 0)
	    2 ((My first car was my mom old car \.)  (first-car)) (0 :gist) 
	 1 (0 dad\'s 0)
	    2 ((My first car was my dad old car \.)  (first-car)) (0 :gist) 
	 1 (0 family 0) 
        2 (0 family gives 0)
           3 ((My first car is a gift from my 2 \.)  (first-car)) (0 :gist)
        2 (0 family give 0)
           3 ((My first car is a gift from my 2 \.)  (first-car)) (0 :gist)
        2 (0 family 0)
           3 ((I used to drive my first car with my 2 \.)  (first-car)) (0 :gist)
     1 (0 friend 0) 
        2 ((I used to drive my first car with my 2 \.)  (first-car)) (0 :gist)
     1 (0 colleague 0) 
        2 ((I used to drive my first car with my 2 \.)  (first-car)) (0 :gist)
     1 (0 neighbour 0) 
        2 ((I used to drive my first car with my 2 \.)  (first-car)) (0 :gist)
     1 (0)
       2 ((NIL Gist \: nothing found for what I remember about my first car \.) (first-car)) (0 :gist)
))
       
       
 (READRULES '*thematic-answer-from-first-car-input*
    '())

 (READRULES '*unbidden-answer-from-first-car-input*
    '())
		
 (READRULES '*question-from-first-car-input*
    '(1 (0 what 2 you 0)
        2 (What do you remember about your first car ?) (0 :gist)
      1 (0 how 2 you 0)
        2 (What do you remember about your first car ?) (0 :gist)
	  1 (0 wh_ 4 hobbies 0)
        2 (What do you remember about your first car ?) (0 :gist)
      ))

(READRULES '*reaction-to-first-car-input*
   '( 1 (1 NEG 1 remember 0) 
       2 (So it was a long time ago\.) (100 :out)
      1 (0 car-brand car-brand-two 0 )
         2 (0 Ford 0)
            3 (Cool\! Ford was very popular\. You remember seeing a lot of Ford coupes around back then\.) (100 :out)
         2 (0 Chevrolet 0)
            3 (Chevy is popular in an international scale\. Nice choice\.) (100 :out)
         2 (0 Cadillac 0)
            3 (A Cadillac\! Must feel good to drive it in the street\.) (100 :out)
         2 (0 car-brand car-brand-two 0)
            3 (You know some people who drive 2 3 back in your days\. Your father lent you a Ford though\. A classic choice\.) (100 :out)
      1 (0 car-brand-two car-brand-two 0 )
         2 (You know some people who drive 2 3 back in your days\. Your father lent you a Ford though\. A classic choice\.) (100 :out)
      1 (0 car-brand 0 )
         2 (0 Ford 0)
            3 (Yes\, Ford was very popular\. You remember seeing a lot of Ford coupes around back then\.) (100 :out)
         2 (0 Chevrolet 0)
            3 (Chevy is popular in an international scale\. Nice choice\.) (100 :out)
         2 (0 Cadillac 0)
            3 (A Cadillac\! Must feel good to drive it in the street\.) (100 :out)
         2 (0 car-brand 0)
            3 (You know some people who used to drive 2 back in your days\. Your father lent you a Ford though\. A classic choice\.) (100 :out)
      1 (0 car-brand-two 0 )
         2 (You know some people who used to drive 2 back in your days\. Your father lent you a Ford though\. A classic choice\.) (100 :out)
      1 (0 shade color 0 )
         2 (0 shade blue 0)
            3 (Blue is your favorite color\! Your first car was sea blue\.) (100 :out)
         2 (0 shade color 0)
            3 (2 3 is a wonderful color\. You would love to have a 3 car\.) (100 :out)
      1 (0 color 0 )
         2 (0 blue 0)
            3 (Blue is a beautiful color\. You also had a blue coupe once\.) (100 :out)
         2 (0 color 0)
            3 (Interesting to know\. You personally had a blue Ford as your graduation gift from your father\.) (100 :out)
      1 (0 gift 0 )
         2 (0 family 0)
            3 (It sounds lovely to get a car as a gift\. Your father gave you a blue Chevy after my graduation from college\.) (100 :out)
         2 (0)
            3 (A car\'s a great gift\.) (100 :out)
      1 (0 family 0)
	     2 (0 mom old car 0)
		   3 (It is so generous when parents buy a car for their kid or give them their own car \.) (100 :out) 
         2 (You love driving with your husband\. Good old time\.) (100 :out)
	 1 (0 NIL Gist 0)
	   2 (My first car can be a very memorable experience\.) (100 :out)
	))
); end of eval-when
