(eval-when (load eval)
  (MAPC 'ATTACHFEAT
  '( (countryside mountain lake river sea beach rural cabin)
    (transportation highway tunnel tunnels motel motels)
    (camping hiking Yellowstone Grand Canyon Yosemite National Park Parks Adirondacks Adirondack)
    (state Alabama Alaska Arizona Arkansas California Colorado Connecticut Delaware Florida Georgia Hawaii
    Idaho Illinois Indiana Iowa Kansas Kentucky Louisiana Maine Maryland Massachusetts Michigan Minnesota
    Mississippi Missouri Montana Nebraska Nevada New Hampshire New Jersey New Mexico New York North Dakota
    Ohio Oklahoma Oregon Pennsylvania Rhode Island South Carolina South Dakota Tennessee Texas Utah Vermont
    Virginia Washington West Virginia Wisconsin Wyoming)
    (city LA NYC SF DC SD Los Angeles San Francisco New York City Washinton DC San Diego Houston Chicago
      Dallas Phoenix Boston Seattle Nashivlle Portland Las Vegas Detroit Philadelphia Miami Atlanta Rochester
      Pittsburgh Montana)
    (Philadelphia Philly)
    (country USA United States Mexico Canada Germany Italy France Switzerland Austria Vienna Belgium Poland Netherland
     Amsterdam Denmark Czechia UK United Kingdom)
    (country-city Toronto Muncih Berlin Frankfurt Rome Milan Paris Strasburg Vienna Amsterdam)
    (family grandchildren grandchild children child daughter daughters son sons spouse wife husband siblings brother brothers sister sisters
      parents mother father grandparents grandmother grandfather cousin cousins uncle aunt)
    (friend friends)
    (unplanned surprises surprise surprising surprised unexpected discover discovery discoveries)
   ))
  
;;	Have you ever taken a fun road trip ?
;;	(0 I 1 never taken 2 road trip 0)  (0 I took 2 road trip 0) 
;;	road-trips
;;	gist-question: (1 have you 4 road trip 4)

(READRULES '*specific-answer-from-road-trips-input*
   '(
     1 (0 city city city 0) ;; e.g. New York City
        2 ((I took a road trip to 2 3 4 \.)  (road-trips)) (0 :gist)
     1 (0 city city 0) 
        2 ((I took a road trip to 2 3 \.)  (road-trips)) (0 :gist)
     1 (0 city 0) 
        2 ((I took a road trip to 2 \.)  (road-trips)) (0 :gist)
     1 (0 state state 0) 
        2 ((I took a road trip to 2 3 \.)  (road-trips)) (0 :gist)
     1 (0 state 0) 
        2 ((I took a road trip to 2 \.)  (road-trips)) (0 :gist) 
     1 (0 country country 0)  ;; e.g. United States
        2 ((I took a road trip to 2 3 \.)  (road-trips)) (0 :gist)
     1 (0 country-city 0)
        2 ((I took a road trip to 2 \.)  (road-trips)) (0 :gist)
     1 (0 country 0)
        2 ((I took a road trip to 2 \.)  (road-trips)) (0 :gist)
     1 (0 family 0) 
        2 ((I took a road trip with my 2 \.)  (road-trips)) (0 :gist)
     1 (0 friend 0) 
        2 ((I took a road trip with my 2 \.)  (road-trips)) (0 :gist)
     1 (0 stranger 0) 
        2 ((I took a road trip with 2 \.)  (road-trips)) (0 :gist)
     1 (0 unplanned 0)
        2 ((I took 2 road trips \.)  (road-trips)) (0 :gist)
     1 (0 Yosemite National Park 0)
        2 ((I took a road trip to 2 3 4 \.)  (road-trips)) (0 :gist)
     1 (0 National Park 0)
        2 ((I took a road trip to 2 3 \.)  (road-trips)) (0 :gist)
     1 (0 camping 0)
        2 ((I took a road trip to 2 \.)  (road-trips)) (0 :gist)
     1 (1 NEG 3 road trip 0) 
        2 ((I have never taken any road trip \.)  (road-trips)) (0 :gist)
     1 (1 NEG 3 road trips 0) 
        2 ((I have never taken any road trip \.)  (road-trips)) (0 :gist)
     1 (1 NEG 3 remember 0) 
        2 ((I have never taken any road trip \.)  (road-trips)) (0 :gist)

     1 (1 NEG 2 unplanned 0) ;; e.g. I don't really like unplanned road trips
        2 ((I have never taken any 4 road trip \.)  (road-trips)) (0 :gist)
     1 (1 NEG 3 family 0) 
        2 ((I have never taken any road trip with my 4 \.)  (road-trips)) (0 :gist)
     1 (0)
       2 ((NIL Gist \: nothing found for if I took any road trip \.) (road-trips)) (0 :gist)
	   ))
       
       
 (READRULES '*thematic-answer-from-road-trips-input*
    '())

 (READRULES '*unbidden-answer-from-road-trips-input*
    '())
		
 (READRULES '*question-from-road-trips-input*
    '(1 (0 what 2 you 0)
        2 (Have you ever taken a fun road trip ?) (0 :gist)
      1 (0 how 2 you 0)
        2 (Have you ever taken a fun road trip ?) (0 :gist)
	    1 (0 wh_ 4 hobbies 0)
        2 (Have you ever taken a fun road trip ?) (0 :gist)
      ))

(READRULES '*reaction-to-road-trips-input*
   '(
    1 (1 have never taken 0) 
       2 (Oh\. Road trip is much fun in your opinion\. However\, some people find it boring or tiring \.) (100 :out)
    1 (0 city city city 0) 
       2 (You have taken a road trip to 2 3 4 with your friends\. They played music during the ride and you have wonderful memories\.) (100 :out)
    1 (0 state state 0) 
       2 (0 New York 0)
          3 (You have taken a road trip to 2 3 City with your friends\. They played music during the ride and you have wonderful memories\.) (100 :out)
       2 (0 state state 0)
          3 (You have never been to 2 3 \, but it must be nice there\.) (100 :out)
    1 (0 city city 0) 
       2 (0 Los Angeles 0)
          3 (You have been to LA just last month\. The weather is great there\.) (100 :out)
       2 (0 San Francisco 0)
          3 (There are a lot of beautiful places along the coastline between LA and San Francisco \. Really want to take a road trip there\.) (100 :out)
       2 (0 Las Vegas 0)
          3 (You really want to take a road trip from SF to Las Vegas with your friends\. They would have so much fun\.) (100 :out)
       2 (0 city city 0)
          3 (You have never been to 2 3 \, but it\'s in your wish list\.) (100 :out)
    1 (0 city 0) 
       2 (0 Boston 0)
          3 (You\'ve taken a road trip to Boston with college friends\. You thought Boston is a nice place to live\.) (100 :out)
       2 (0 Philadelphia 0)
          3 (You\'ve taken a road trip to Philly\. You love the restraunts there\.) (100 :out)
       2 (0 LA 0)
          3 (You have been to LA just last month\. The weather is great there\.) (100 :out)
       2 (0 SF 0)
          3 (There are a lot of beautiful places along the coastline between LA and SF\. Really want to take a road trip there\.) (100 :out)
       2 (0 NYC 0)
          3 (You have taken a road trip to NYC with my friends\. They played music during the ride and I have wonderful memories\.) (100 :out)
       2 (0 city 0)
          3 (You have never been to 2 \, but it\'s in your wish list\.) (100 :out)
     1 (0 state 0) 
       2 (0 California 0)
          3 (There are a lot of beautiful places along the coastline between LA and San Franci\. Really want to take a road trip there\.) (100 :out)
       2 (0 Pennsylvania 0)
          3 (You have taken a road trip to Philly\. You love the restraunts there\.) (100 :out)
       2 (0 state 0)
          3 (You have never been to 2 \, but it\'s in your wish list\.) (100 :out)
     1 (0 country country 0) 
    ;   2 (0 United States 0)
     ;     3 (Nice to take road trips in my own country\.) (100 :out)
       2 (0 United Kingdom 0)
          3 (You wish you could take a road trip in UK\, but it\'s too far away for you \.) (100 :out)
       2 (0 city city 0)
          3 (You have never been to 2 3 \, but it\'s in your wish list\.) (100 :out)
     1 (0 country 0) 
       2 (0 Germany 0)
          3 (You have been to Germany several times\. Love their beers\.) (100 :out)
       2 (0 France 0)
          3 (Love French cuisines\. I must had a good time there\.) (100 :out)
       2 (0 Italy 0)
          3 (Love their great artworks\. Wish you could take a few road trips there and also enjoy their countryside scenes\.) (100 :out)
       2 (0 country 0)
          3 (You have never been to 2 3 \, but it\'s in your wish list\.) (100 :out)
     1 (0 country-city 0) 
       2 (0 Munich 0)
          3 (You have been to Munich several times\. It is a diverse and beautiful city\.) (100 :out)
       2 (0 Paris 0)
          3 (Have you visited the Eiffel Tower\? I had a great time there with my husband\.) (100 :out)
       2 (0 Rome 0)
          3 (Love their great artworks\. Wish you could take a few road trips there and also enjoy their countryside scenes\.) (100 :out)
       2 (0 counrty-cities 0)
          3 (You have never been to 2 \, but it\'s in your wish list\.) (100 :out)
     1 (1 NEG 1 like unexpected road trips 0)
       2 (An unprepared road trip can be very dangerous\.) (100 :out)
     1 (0 unexpected 0)
       2 (One can always learn something from new discoveries\.) (100 :out)
     1 (0 family 0)
       2 (Taking a road trip together is a great way to create unforgettable family memories\.) (100 :out)
     1 (0 friend 0)
       2 (You love to take road trips with your friends\. They would talk along the drive and it\'s a lot of fun\.) (100 :out)
     1 (0 Yosemite National Park 0)
       2 (Going to 2 3 4 can be a wonderful experience\. I just should make sure I have a good map with me \.) (100 :out)
     1 (0 National Park 0)
       2 (Going to 2 3 can be a wonderful experience\. I just should make sure I have a good map with me \.) (100 :out)
     1 (0 camping 0)
       2 (Going to 2 can be a wonderful experience\. I just should make sure I have a good map with me \.) (100 :out)
	 1 (0 NIL Gist 0)
	   2 (You never liked being stuck in a car for a while\, but it sounds like road trips can be fun\.) (100 :out)
	))
); end of eval-when
