(eval-when (load eval)
  (MAPC 'ATTACHFEAT
  '((snow snowy snowing snows blizzard ice)
     (sun sunny)
    (rain rainy)
	(cold colder freezing frigid icy)
	(moderate pleasant mild)
	(have had has)
    (lot lots)
	(season-names fall spring summer winter)
	(like liked loved love)
  ))
    
;; (how did you like the weather in your hometown ?)
;;	(hometown-weather)
;;		from-hometown-weather-input
;;			(0 the weather in my hometown 0)
;;			gist-question:(3 how 2 like the weather 2 hometown 0)

 (READRULES '*specific-answer-from-hometown-weather-input*
   '( 
     1 (0 four seasons 0) 
        2 ((The weather in my hometown has all four seasons \.)  (hometown-weather)) (0 :gist) 		
     1 (0 hot 0)
       2 (0 hot 2 summer 0)
         3 ((The weather in my hometown is hot during summer \.) (hometown-weather)) (0 :gist)
       2 (0 summer 2 hot 0)
         3 ((The weather in my hometown is hot during summer \.) (hometown-weather)) (0 :gist)
       2 (0 NEG 1 like 1 hot 0) 
         3 ((I do not like the weather to be hot \.)  (hometown-weather)) (0 :gist) 		
       2 (0 not 1 hot 0)
	     3 ((the weather in my hometown is not too hot \.)  (hometown-weather)) (0 :gist) 		
       2 ((probably the weather in my hometown is hot \.)  (hometown-weather)) (0 :gist) 		
     
     1 (0 snow 0)
        2 (0 snow 2 winter 0)
         3 ((The weather in my hometown is snowy during winter \.) (hometown-weather)) (0 :gist)
        2 (0 winter 5 snow 0)
         3 ((The weather in my hometown is snowy during winter \.) (hometown-weather)) (0 :gist)
        2 (0 NEG 1 like 2 snow 0) 
         3 ((I do not like the weather in my hometowen to be snowy \.)  (hometown-weather)) (0 :gist) 		
        2 ((probably the weather in my hometown is snowy \.)  (hometown-weather)) (0 :gist) 		       
     1 (0 rain 0)
	    2 (0 rain 2 season-names 0)
          3 ((The weather in my hometown is rainy during 4 \.) (hometown-weather)) (0 :gist)
        2 (0 season-names 2 rain 0)
         3 ((The weather in my hometown is rainy during 2 \.) (hometown-weather)) (0 :gist)
        2 (0 we have 2 lot 1 rain 0) 
         3 ((the weather in my hometown is rainy \.)  (hometown-weather)) (0 :gist) 		
        2 (0 it be 1 rain 0) 
         3 ((the weather in my hometown is rainy \.)  (hometown-weather)) (0 :gist) 		
        2 ((probably the weather in my hometown is rainy \.)  (hometown-weather)) (0 :gist) 		
     
    1 (0 cold 0)
       2 (0 cold 2 winter 0)
         3 ((The weather in my hometown is cold during winter \.) (hometown-weather)) (0 :gist)
       2 (0 winter 3 cold 0)
         3 ((The weather in my hometown is cold during winter \.) (hometown-weather)) (0 :gist)
       2 (0 we have 2 lot 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it got 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it be 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
       2 (0 weather be 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
       2 ((probably the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
    
    1 (0 moderate 0)
       2 (0 moderate 2 season-names 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
       2 (0 season-names 2  moderate 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
       2 (0 season-names it is 4 moderate 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
       2 (0 we have 3 moderate 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it be 3 moderate 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it is got 3 moderate 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
       2 ((probably the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
     
	 1 (0 warm 0)
       2 (0 warm 2 season-names 0) 
         3 ((the weather in my hometown is warm \.)  (hometown-weather)) (0 :gist) 		
       2 (0 season-names 2  warm 0) 
         3 ((the weather in my hometown is warm \.)  (hometown-weather)) (0 :gist) 		
       2 (0 season-names it is 4 warm 0) 
         3 ((the weather in my hometown is warm \.)  (hometown-weather)) (0 :gist) 		
       2 (0 we have 3 warm 0) 
         3 ((the weather in my hometown is warm \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it be 3 warm 0) 
         3 ((the weather in my hometown is warm \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it is got 3 warm 0) 
         3 ((the weather in my hometown is warm \.)  (hometown-weather)) (0 :gist) 		
       2 ((probably the weather in my hometown is warm \.)  (hometown-weather)) (0 :gist) 		


       
     1 (0 I like 2 seasons 0) 
        2 ((I like the weather in my hometown to have all the seasons \.)  (hometown-weather)) (0 :gist) 		
     1 (0 I like 2 change 2 seasons 0) 
        2 ((I like the weather in my hometown to have all the seasons \.)  (hometown-weather)) (0 :gist) 		
     1 (0 sun 0)
	    2 (0 I like 2 sun 0) 
          3 ((I like the weather in my hometown to be sunny \.)  (hometown-weather)) (0 :gist) 		
        2 (0 NEG enough 1 sun 0)
	      3 ((the weather in my hometown is not enough sunny \.) (hometown-weather)) (0 :gist)
	    2 ((probably the weather in my hometown is sunny \.)  (hometown-weather)) (0 :gist) 		
   
    1 (0 same as rochester  0) 
        2 ((the weather in my hometown is same as rochester \.)  (hometown-weather)) (0 :gist) 		
     1 (0 same as here 3  0) 
        2 ((the weather in my hometown is same as rochester \.)  (hometown-weather)) (0 :gist) 		 
     1 (0 season-names 0) 
	    2 (0 I like 2 season-names 0) 
          3 ((I like that the weather in my hometown has all the seasons \.)  (hometown-weather)) (0 :gist) 		
        2 (0 season-names 0) 
          3 ((I talked about how seasons and the weather in my hometown is \.)  (hometown-weather)) (0 :gist) 		
     1 (0 NEG 1 like 2 weather 0) 
        2 ((I do not like the weather in my hometown \.)  (hometown-weather)) (0 :gist) 		
     
	 1 (0)
       2 ((NIL Gist \: nothing found for how the weather in my hometown is \.) (hometown-weather)) (0 :gist)
	
   ))
       
       
 (READRULES '*thematic-answer-from-hometown-weather-input*
    '())

 (READRULES '*unbidden-answer-from-hometown-weather-input*
    '())
		
 (READRULES '*question-from-hometown-weather-input*
    '())

(READRULES '*reaction-to-hometown-weather-input*
'(1 (0 NEG like 0 hot 0)
  2 (If I am not a fan of hot weather\, then I must like Rochester\!) (100 :out)
1 (0 hot 0)
  2 (You lived in Texas for a long time\, so you know hot weather very well\. Rochester is a big change for you \.) (100 :out)
1 (0 NEG like 0 snowy 0)
  2 (If I do not like snow\, then it should be hard for me in Rochester\!) (100 :out)
1 (0 snowy 0)
  2 (Oh\, you love snow\. that\'s really fun\. ) (100 :out)
1 (0 rainy 0)
  2 (You love rain\, especially the weather after a heavy rain\.) (100 :out)
1 (0 cold 0)
  2 (Oh\, in your opinion cold weather is better than hot\. Just be sure to stay warm when I am there\!) (100 :out)
1 (0 moderate 0)
  2 (That\'s nice\. You love when it is around seventy five outside with a nice sunny weather\. Though it does happen only during Summer in Rochester \.) (100 :out)
1 (0 warm 0)
  2 (That\'s nice\. You love when it is around seventy five outside with a nice sunny weather\. Though it does happen only during Summer in Rochester \.) (100 :out)
1 (0 sun 0)
  2 (0 not enough sun 0)
     3 (You would not like hot weather but sometime\, you really miss sun here in Rochester \.) (100 :out)
  2 (You would also like sunny weather\. However\, you could not stand when it is too hot \.) (100 :out)
1 (0 same as rochester 0)
  2 (So I must be used to this kind of weather\.) (100 :out)
1 (0 all the seasons 0)
  2 (That\'s really great to experience all seasons\.) (100 :out)
1 (0 not like the weather 0)
  2 (Oh\, you are sorry if I don\'t like that weather\. You believe I can always find something to enjoy in any weather\.) (100 :out)  
1 (0 NIL Gist 0)
  2 (You find the weather to be a pretty important factor of where you want to live\.) (100 :out)
	))
); end of eval-when
